#!/usr/bin/perl -w

use strict;
BEGIN {
	$0=~ /(.*?)([^\/]*)$/s;
	unshift @INC, $1;
	require 'newperl.lib';
}



sub usage {
	$0=~ /([^\/]*)$/;
	print "$1 some/path/perlfile

  Creates and opens executable script in \$EDITOR.
";
	exit;
}

usage() unless @ARGV;

my @paths;
for (@ARGV) {
	if (/^--?h(elp)?$/) {
		usage();
	} else {
		create ($_);
	}
}

edit (15, @paths);


sub create {
	my ($path)=@_;
	
	if (-e $path) {
		warn "File $path does already exist!\n";
		push @paths,$path;# edit the old file
	} else {
		$path=~ /(.*?)[^\/]*$/ or die;
		my $folder= $1;
		if (length $folder) {
			if (-d $folder) {
				# ok
			} else {
				$|=1;
				print "The folder '$folder' does not exist. Create it? [y/n] ";
				my $a=<STDIN>;
				if ($a=~ /^[jy]/) {
					system "/bin/mkdir",$folder;
				} else {
					warn "Cancel.\n";
					return;
				}
			}
		}
		if (open OUT,">$path") {
			my $copy= copy();
			print OUT <<"END" or warn "Error while writing: $!";
#!/usr/bin/perl -w

$copy
#
# \$Id\$

use strict;

use vars qw();


END

			close OUT;
			system "/bin/chmod","+x",$path;
			push @paths,$path;
		} else {
			warn "Could not open file '$path': $!\n";
		}
	}
}

