#!/usr/bin/perl -w

use strict;

#use lib '/home/chris/Projekt/CVS_2ndcheckouts/';
use lib ".";

use My::IOException;

try { 
	print "Hallo Welt\n";
	open IN, "ASDVASFDVAF" or throw My::IOException '<title>Blabla</title><body>Hehehe das geht nicht</body>';
	try {
		print <IN> || die "XX";
		print "Hallo\n";
	}
	finally {
		close IN;
	}
}

